use std::path::Path;

use crate::error::{HxError, HxResult};

const HTML_HEAD: &str = r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Episode: {run_id}</title>
<style>
{style}
</style>
</head>
<body>
<div class="container">
<header class="episode-header">
  <h1>Episode</h1>
  <code class="run-id">{run_id}</code>
  <span class="status-badge {status_class}">{status_label}</span>
</header>
<main>
{sections}
</main>
<footer class="episode-footer">
  <p>Generated by HighHarness &middot; {timestamp}</p>
</footer>
</div>
</body>
</html>"#;

const HTML_STYLE: &str = r#"
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--bg:#0d1117;--surface:#161b22;--border:#30363d;--text:#c9d1d9;--text-muted:#8b949e;--accent:#58a6ff;--green:#3fb950;--red:#f85149;--orange:#d29922;--font:-apple-system,BlinkMacSystemFont,'Segoe UI',Noto Sans,Helvetica,Arial,sans-serif;--mono:'SF Mono','Cascadia Code','Fira Code','Consolas',monospace}
body{background:var(--bg);color:var(--text);font-family:var(--font);line-height:1.6;padding:0}
.container{max-width:960px;margin:0 auto;padding:24px}
.episode-header{margin-bottom:32px;padding-bottom:24px;border-bottom:1px solid var(--border)}
.episode-header h1{font-size:20px;font-weight:600;color:var(--text-muted);margin-bottom:8px}
.episode-header .run-id{font-family:var(--mono);font-size:14px;color:var(--accent)}
.status-badge{display:inline-block;margin-left:12px;padding:2px 10px;border-radius:12px;font-size:12px;font-weight:600;vertical-align:middle}
.status-closed{background:rgba(63,185,80,0.15);color:var(--green);border:1px solid rgba(63,185,80,0.3)}
.status-open{background:rgba(210,153,34,0.15);color:var(--orange);border:1px solid rgba(210,153,34,0.3)}
section.section-card{background:var(--surface);border:1px solid var(--border);border-radius:8px;margin-bottom:16px;overflow:hidden}
.section-card h2{font-size:14px;font-weight:600;color:var(--text-muted);padding:12px 16px;border-bottom:1px solid var(--border);text-transform:uppercase;letter-spacing:0.5px}
.section-card .section-body{padding:16px;font-size:14px}
.section-card .section-body p{margin-bottom:8px}
.section-card .section-body p:last-child{margin-bottom:0}
.section-card .section-body ul,.section-card .section-body ol{padding-left:20px;margin-bottom:8px}
.section-card .section-body li{margin-bottom:4px}
.section-card .section-body table{border-collapse:collapse;width:100%;font-size:13px}
.section-card .section-body th,.section-card .section-body td{padding:6px 10px;border:1px solid var(--border);text-align:left}
.section-card .section-body th{background:rgba(48,54,61,0.5);font-weight:600;color:var(--text-muted)}
.json-block{background:#010409;border:1px solid var(--border);border-radius:6px;padding:12px;margin:8px 0;overflow-x:auto;font-family:var(--mono);font-size:12px;line-height:1.5;white-space:pre-wrap;word-break:break-all}
.json-string{color:#a5d6ff}.json-number{color:#79c0ff}.json-boolean{color:#d2a8ff}.json-null{color:#8b949e}.json-key{color:#7ee787}
.gate-row{display:flex;align-items:center;gap:8px;padding:8px 0;border-bottom:1px solid var(--border)}
.gate-row:last-child{border-bottom:none}.gate-name{font-weight:600;min-width:100px;font-size:13px}
.gate-pass{color:var(--green)}.gate-fail{color:var(--red)}
.hash-display{font-family:var(--mono);font-size:13px;color:var(--text-muted);word-break:break-all;background:rgba(88,166,255,0.08);border:1px solid rgba(88,166,255,0.15);border-radius:6px;padding:12px}
.episode-footer{text-align:center;padding:24px 0 0;color:var(--text-muted);font-size:12px}
.table-wrap{overflow-x:auto}
.empty{color:var(--text-muted);font-style:italic}
"#;

/// Render an episode markdown file as a self-contained HTML report.
///
/// If `output` is `Some(path)`, the HTML is written to that file.
/// If `output` is `None`, the HTML is printed to stdout.
pub fn render(episode_path: &Path, output: Option<&Path>) -> HxResult<()> {
    let raw = std::fs::read_to_string(episode_path).map_err(HxError::Io)?;
    let html = build_html(&raw)?;
    match output {
        Some(path) => std::fs::write(path, &html).map_err(HxError::Io)?,
        None => println!("{}", html),
    }
    Ok(())
}

struct Section {
    name: String,
    body: String,
}

fn parse_sections(raw: &str) -> (String, Vec<Section>) {
    let mut run_id = String::new();
    let mut sections: Vec<Section> = Vec::new();
    let mut current_name = String::new();
    let mut current_body = String::new();

    for line in raw.lines() {
        if let Some(id) = line.strip_prefix("# Episode ") {
            run_id = id.trim().to_string();
            continue;
        }
        if let Some(name) = line.strip_prefix("## ") {
            if !current_name.is_empty() {
                sections.push(Section {
                    name: std::mem::take(&mut current_name),
                    body: std::mem::take(&mut current_body),
                });
            }
            current_name = name.trim().to_string();
            continue;
        }
        if !current_name.is_empty() {
            if !current_body.is_empty() {
                current_body.push('\n');
            }
            current_body.push_str(line);
        }
    }
    if !current_name.is_empty() {
        sections.push(Section {
            name: current_name,
            body: current_body,
        });
    }

    (run_id, sections)
}

fn has_episode_hash(raw: &str) -> bool {
    raw.contains("## Episode hash")
}

fn build_html(raw: &str) -> HxResult<String> {
    let (ref run_id, sections) = parse_sections(raw);
    let run_id_display: &str = if run_id.is_empty() {
        "unknown"
    } else {
        run_id.as_str()
    };

    let closed = has_episode_hash(raw);
    let status_class = if closed {
        "status-closed"
    } else {
        "status-open"
    };
    let status_label = if closed { "Closed" } else { "Open" };

    let mut section_html = String::new();
    for section in &sections {
        section_html.push_str(&render_section(section));
    }

    let timestamp = chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ").to_string();

    let style = HTML_STYLE.trim();
    let out = HTML_HEAD
        .replace("{run_id}", run_id_display)
        .replace("{status_class}", status_class)
        .replace("{status_label}", status_label)
        .replace("{sections}", &section_html)
        .replace("{timestamp}", &timestamp)
        .replace("{style}", style);

    Ok(out)
}

fn render_section(section: &Section) -> String {
    let slug: String = section
        .name
        .to_lowercase()
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '-' {
                c
            } else {
                '_'
            }
        })
        .collect();

    let body = match section.name.as_str() {
        "Verification report" => render_verification(&section.body),
        "Tool calls" if !section.body.trim().is_empty() => render_tool_calls(&section.body),
        "Episode hash" => render_hash(&section.body),
        _ => render_text_body(&section.body),
    };

    format!(
        r#"<section class="section-card" id="sec-{slug}">
<h2>{name}</h2>
<div class="section-body">{body}</div>
</section>
"#,
        slug = slug,
        name = escape_html(&section.name),
        body = body
    )
}

fn render_text_body(body: &str) -> String {
    let trimmed = body.trim();
    if trimmed.is_empty() {
        return r#"<p class="empty">—</p>"#.to_string();
    }

    if trimmed.contains('|') && trimmed.lines().any(|l| l.starts_with('|')) {
        let mut table_rows: Vec<String> = Vec::new();
        for line in trimmed.lines() {
            if line.starts_with('|') {
                let cols: Vec<&str> = line
                    .trim_start_matches('|')
                    .trim_end_matches('|')
                    .split('|')
                    .collect();
                let cells: Vec<String> = cols
                    .iter()
                    .map(|c| {
                        let t = c.trim();
                        if t.chars().all(|ch| ch == '-' || ch == ':') {
                            String::new()
                        } else {
                            format!("<td>{}</td>", escape_html(t))
                        }
                    })
                    .filter(|c| !c.is_empty())
                    .collect();
                if !cells.is_empty() {
                    table_rows.push(format!("<tr>{}</tr>", cells.join("")));
                }
            }
        }
        if !table_rows.is_empty() {
            return format!(
                r#"<div class="table-wrap"><table>{}</table></div>"#,
                table_rows.join("\n")
            );
        }
    }

    let mut html = String::new();
    let mut in_list = false;

    for line in trimmed.lines() {
        if line.starts_with("- ") || line.starts_with("* ") {
            if !in_list {
                html.push_str("<ul>\n");
                in_list = true;
            }
            let item = line
                .strip_prefix("- ")
                .or_else(|| line.strip_prefix("* "))
                .unwrap_or(line);
            if item.starts_with("**") && item.ends_with("**") {
                let c = &item[2..item.len() - 2];
                html.push_str(&format!("<li><strong>{}</strong></li>\n", escape_html(c)));
            } else {
                html.push_str(&format!("<li>{}</li>\n", escape_html(item)));
            }
        } else {
            if in_list {
                html.push_str("</ul>\n");
                in_list = false;
            }
            if line.trim().is_empty() {
                continue;
            }
            html.push_str(&format!("<p>{}</p>\n", escape_html(line)));
        }
    }
    if in_list {
        html.push_str("</ul>\n");
    }

    html
}

fn render_verification(body: &str) -> String {
    let trimmed = body.trim();
    if trimmed.is_empty() {
        return r#"<p class="empty">—</p>"#.to_string();
    }

    let mut html = String::new();

    if let Ok(v) = serde_json::from_str::<serde_json::Value>(trimmed) {
        if let Some(all_met) = v.get("all_met").and_then(|x| x.as_bool()) {
            let badge = if all_met {
                r#"<span class="gate-pass">&#10003; All criteria met</span>"#
            } else {
                r#"<span class="gate-fail">&#10007; Criteria not met</span>"#
            };
            html.push_str(&format!(
                r#"<div style="margin-bottom:12px;font-size:16px;font-weight:600">{}</div>"#,
                badge
            ));
        }

        html.push_str(r#"<div style="margin-bottom:12px">"#);
        for gate in &["syntactic", "functional", "semantic", "regression"] {
            if let Some(g) = v.get(*gate) {
                let passed = g.get("pass").and_then(|x| x.as_bool()).unwrap_or(false);
                let cls = if passed { "gate-pass" } else { "gate-fail" };
                let icon = if passed { "&#10003;" } else { "&#10007;" };
                let name = format!("{}{}", (*gate)[..1].to_uppercase(), &gate[1..]);
                html.push_str(&format!(
                    r#"<div class="gate-row"><span class="gate-name {}">{} {}</span></div>"#,
                    cls, icon, name
                ));
            }
        }
        html.push_str("</div>");

        let json_str = serde_json::to_string_pretty(&v).unwrap_or_else(|_| trimmed.to_string());
        html.push_str(&format!(
            r#"<pre class="json-block">{}</pre>"#,
            syntax_highlight_json(&json_str)
        ));
    } else {
        html.push_str(&format!(
            r#"<pre class="json-block">{}</pre>"#,
            escape_html(trimmed)
        ));
    }

    html
}

fn render_tool_calls(body: &str) -> String {
    let trimmed = body.trim();
    if trimmed.is_empty() {
        return r#"<p class="empty">—</p>"#.to_string();
    }

    let mut html = String::new();
    for line in trimmed.lines() {
        let l = line.strip_prefix("- ").unwrap_or(line).trim();
        if l.is_empty() {
            continue;
        }
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(l) {
            let pretty = serde_json::to_string_pretty(&v).unwrap_or_else(|_| l.to_string());
            html.push_str(&format!(
                r#"<pre class="json-block">{}</pre>"#,
                syntax_highlight_json(&pretty)
            ));
        } else {
            html.push_str(&format!("<p>{}</p>\n", escape_html(l)));
        }
    }

    html
}

fn render_hash(body: &str) -> String {
    let t = body.trim();
    let hash = t.strip_prefix("SHA-256: ").unwrap_or(t);
    format!(
        r#"<div class="hash-display">SHA-256: <strong>{}</strong></div>"#,
        escape_html(hash.trim())
    )
}

fn syntax_highlight_json(json: &str) -> String {
    let mut out = String::new();
    let mut chars = json.chars().peekable();

    while let Some(c) = chars.next() {
        match c {
            '"' => {
                let mut s = String::new();
                s.push('"');
                loop {
                    match chars.next() {
                        None => break,
                        Some('\\') => {
                            s.push('\\');
                            s.push(chars.next().unwrap_or('\\'));
                        }
                        Some('"') => {
                            s.push('"');
                            break;
                        }
                        Some(ch) => s.push(ch),
                    }
                }
                let inner = &s[1..s.len().saturating_sub(1)];
                if !inner.is_empty() && inner.chars().all(|ch| ch.is_alphanumeric() || ch == '_') {
                    out.push_str(&format!(
                        r#"<span class="json-key">{}</span>"#,
                        escape_html(&s)
                    ));
                } else {
                    out.push_str(&format!(
                        r#"<span class="json-string">{}</span>"#,
                        escape_html(&s)
                    ));
                }
            }
            '0'..='9' | '-' => {
                let mut n = String::new();
                n.push(c);
                while let Some(&next) = chars.peek() {
                    if next.is_ascii_digit()
                        || next == '.'
                        || next == 'e'
                        || next == 'E'
                        || next == '+'
                    {
                        n.push(next);
                        chars.next();
                    } else {
                        break;
                    }
                }
                out.push_str(&format!(
                    r#"<span class="json-number">{}</span>"#,
                    escape_html(&n)
                ));
            }
            't' | 'f' => {
                let mut w = String::new();
                w.push(c);
                for _ in 0..(if c == 't' { 3 } else { 4 }) {
                    w.push(chars.next().unwrap_or(' '));
                }
                let cls = if w == "true" || w == "false" {
                    "json-boolean"
                } else {
                    out.push_str(escape_html(&w).as_str());
                    continue;
                };
                out.push_str(&format!(
                    r#"<span class="{}">{}</span>"#,
                    cls,
                    escape_html(&w)
                ));
            }
            'n' => {
                let w: String = std::iter::once(c)
                    .chain((0..3).map(|_| chars.next().unwrap_or(' ')))
                    .collect();
                if w == "null" {
                    out.push_str(&format!(
                        r#"<span class="json-null">{}</span>"#,
                        escape_html(&w)
                    ));
                } else {
                    out.push_str(escape_html(&w).as_str());
                }
            }
            _ => {
                out.push(c);
            }
        }
    }

    out
}

fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_empty_episode() {
        let raw = "# Episode test-run-1\n\n## Task spec\n\n## Plan\n";
        let (id, sections) = parse_sections(raw);
        assert_eq!(id, "test-run-1");
        assert_eq!(sections.len(), 2);
        assert_eq!(sections[0].name, "Task spec");
        assert_eq!(sections[1].name, "Plan");
    }

    #[test]
    fn parse_full_episode() {
        let raw = "# Episode run-abc\n\n## Task spec\ndo the thing\n\n## Plan\nstep 1\nstep 2\n\n## Episode hash\nSHA-256: abc123\n";
        let (id, sections) = parse_sections(raw);
        assert_eq!(id, "run-abc");
        assert_eq!(sections.len(), 3);
        assert!(sections[1].body.contains("step 2"));
    }

    #[test]
    fn detect_closed_vs_open() {
        assert!(has_episode_hash("## Episode hash\nSHA-256: abcd\n"));
        assert!(!has_episode_hash("## Task spec\ncontent\n"));
    }

    #[test]
    fn html_output_contains_key_elements() {
        let raw = "# Episode demo-run\n\n## Task spec\nAdd version flag\n\n## Verification report\n{\"all_met\":true,\"syntactic\":{\"pass\":true}}\n\n## Episode hash\nSHA-256: aabbccdd\n";
        let html = build_html(raw).unwrap();
        assert!(html.contains("demo-run"));
        assert!(html.contains("Closed"));
        assert!(html.contains("SHA-256"));
        assert!(html.contains("All criteria met"));
    }

    #[test]
    fn escape_html_entities() {
        assert_eq!(escape_html("<script>"), "&lt;script&gt;");
        assert_eq!(escape_html("\"quote\""), "&quot;quote&quot;");
        assert_eq!(escape_html("a & b"), "a &amp; b");
    }
}
